hello/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

music/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.index, name='index'),  # homepage of /music
    path('<int:album_id>/favorite/', views.favorite, name='favorite'),
    path('<int:album_id>/', views.detail, name='detail'),
]

music/models.py
from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=400)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return "%s - %s" % (self.album_title, self.artist)


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return "%s in %s, %s" % (self.song_title, self.album, self.file_type)

music/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Album, Song


# Create your views here.
def index(request):
    all_albums = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = {
        'all_albums': all_albums,
    }
    return HttpResponse(template.render(context, request))


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    context = {
        'album_id': album_id,
        'album': album
    }
    return render(request, 'music/album_index.html', context)


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['fav'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/album_index.html', {
            'album': album,
            'error_message': "you didn't select a favorite song",
        })
    else:
        if selected_song.is_favorite:
            selected_song.is_favorite = False
        else:
            selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/album_index.html', {'album': album})

music/templates/music/album_index.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}  <!-- For every song in album -->
        <input type="radio" id="song{{ forloop.counter }}" name="fav" value="{{ song.id }}" />  <!-- Add button for each-->
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698904-icon-23-star-128.png" width="32" height="32" />
            {% endif %}
        </label> <br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
<!-- Loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

            </button>
            <a class="navbar-brand" href="{% url 'music:index' %]">
                Legato
            </a>
        </div>
    </div>
</nav>

{% if all_albums %}
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h2>No albums</h2>
{% endif %}